name: Build and test OCaml module
inputs:
  extra-packages:
    description: Extra packages to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v1
    - name: Install ocaml
      uses: ocaml/setup-ocaml@v2
    - name: Install module
      run: opam install --cli=2.1 --with-test --confirm-level=unsafe-yes . ${{ inputs.extra-packages }}
      shell: bash
