name: Build and test OCaml module
inputs:
  extra-packages:
    description: Extra packages to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v1
    - name: Install ocaml
      uses: ocaml/setup-ocaml@v2
    - name: Install module
      if: ${{ runner.os == "Windows" }}
      run: |
        opam depext -iy --with-test . ${{ inputs.extra-packages }}
      shell: pwsh
    - name: Install module
      if: ${{ runner.os != "Windows" }}
      run: |
        opam -cli=2.1 --confirm-level=unsafe-yes --with-test . ${{ inputs.extra-packages }}
      shell: bash
