name: Build and test OCaml module
inputs:
  extra-packages:
    description: Extra packages to install
    required: false
    default: ''
  ocaml-compiler:
    description: OCaml compiler
    required: false
    default: 4.14.x
runs:
  using: composite
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v1
    - name: Install ocaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ inputs.ocaml-compiler }}
        opam-depext: true
        opam-pin: true
    - name: Install module
      if: runner.os == 'Windows'
      run: |
        opam install --verbose -y --with-test . ${{ inputs.extra-packages }}
      shell: pwsh
    - name: Install module
      if: runner.os != 'Windows'
      run: |
        opam --cli=2.1 install --verbose --confirm-level=unsafe-yes --with-test . ${{ inputs.extra-packages }}
      shell: bash
