name: Build and test OCaml module
inputs:
  extra-packages:
    description: Extra packages to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v1
    - name: Install ocaml
      uses: ocaml/setup-ocaml@v2
      with:
        opam-depext: true
        opam-pin: true
    - name: Install module
      if: runner.os == 'Windows'
      run: |
        opam install -y --with-test *.opam ${{ inputs.extra-packages }}
      shell: pwsh
    - name: Install module
      if: runner.os != 'Windows'
      run: |
        opam --cli=2.1 install --confirm-level=unsafe-yes --with-test *.opam ${{ inputs.extra-packages }}
      shell: bash
