name: Build and test OCaml module
inputs:
  extra-packages:
    description: Extra packages to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v1
    - name: Install ocaml
      uses: ocaml/setup-ocaml@v2
    - name: Executable extension
      id: exe_ext
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          echo "##[set-output name=opam_exe;]opam.exe --depext -yi"
          echo "##[set-output name=opam_path;]${PATH}:/d/cygwin/bin"
        else
          echo "##[set-output name=opam_exe;]opam install --cli=2.1 --confirm-level=unsafe-yes"
          echo "##[set-output name=opam_path;]$PATH"
        fi
      shell: bash
    - name: Install module
      run: |
        ${{ steps.exe_ext.outputs.opam_exe }} --with-test . ${{ inputs.extra-packages }}
      env:
        PATH: ${{ steps.exe_ext.outputs.opam_path }}
      shell: bash
