name: Build and test OCaml module
inputs:
  extra-packages:
    description: Extra packages to install
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout latest code
      uses: actions/checkout@v1
    - name: Install ocaml
      uses: ocaml/setup-ocaml@v2
    - name: Select shell
      id: shell
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          echo "##[set-output name=shell;]pwsh"
        else
          echo "##[set-output name=shell;]bash"
        fi
      shell: bash
    - name: Install module
      run: |
        opam depext -iy --with-test . ${{ inputs.extra-packages }}
      shell: ${{ steps.shell.outputs.shell }}
